### ISSUE TITLE
Schematics don't display name after decimal points

### ISSUE THREAD

**Issue by jxu** [OpenRedstoneEngineers/schems-website#2]
`rdf_plot_1.4` shows up as "rdf_plot_1"

![schematics](https://user-images.githubusercontent.com/7989982/82849317-5466f180-9ec5-11ea-89cb-9e38eecfef9f.PNG)

**Comment by Nickster258** [comment]
We are currently [rewriting the schematics system](https://github.com/OpenRedstoneEngineers/Schemati) and won't be updating this existing project.
